version: 1.0.{build}
os: Visual Studio 2015
install:
- cmd: >-
    set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    dnvm install 1.0.0-rc1-update1
before_build:
- cmd: dnu restore
build:
  verbosity: normal